Director;Movie Genre|Movie Genre Count
Briano Andriveau;Comedy|4;Drama|5
Salaidh Neenan;Comedy|1
Ingrim Thrasher;Comedy|4
Rubi Philipps;Comedy|3
Alric Jahn;Comedy|4
Dorette Cushion;Comedy|3;Drama|7
Ewan Auld;Comedy|6;Drama|6
Zack Illsley;Comedy|4
Darleen Blasiak;Comedy|5;Drama|7
Rodolphe McCrie;Comedy|3
Bobinette Von Welden;Drama|3
Shepard Cuddihy;Comedy|1
Harli Buss;Drama|5
Mariya Pleasants;Comedy|2;Drama|3
Dare Espie;Drama|4
Royall Freddi;Drama|2
Gabbey Darragon;Drama|5
Janine Friedlos;Comedy|3
Quintina Knolles-Green;Drama|3
Filide Barttrum;Drama|2
Caryl Huyche;Comedy|2;Drama|3
Sarah Adshead;Drama|1
Tiffanie Barstow;Comedy|3
Otha Gryglewski;Comedy|1
Ianthe Teesdale;Drama|3
Holmes Sidey;Drama|7
Nina Agate;Comedy|3
Sal Wythill;Comedy|4
Easter Liffey;Drama|2
Barnabas Hawkett;Drama|3
Lothaire Prisk;Drama|2
Cristiano Skyner;Drama|4
Liane Antyshev;Comedy|3
Francesca Ranshaw;Drama|2
Yanaton Raylton;Comedy|3
Jeane Woehler;Drama|2
Harli Croydon;Comedy|1
Belinda Skates;Comedy|1
Afton Deroche;Comedy|4
Alisa Charteris;Drama|5
Zaneta Gianilli;Drama|2
Allen Baughn;Drama|3
Shirline Yuille;Drama|2
Emmeline Andrei;Comedy|1
Nickey Wilhelmy;Comedy|2
Thelma Hearty;Drama|4
Ruddy Charkham;Drama|3
Ludovika Obal;Comedy|7
Pren Davson;Comedy|2
Faustina Malkinson;Drama|8
Kandy Gilfillan;Comedy|3
Gunilla Mateja;Drama|6
Keelby Hosten;Drama|7
Kirbee Kimmel;Comedy|4;Drama|8
Vincents Clemont;Drama|2
Carma Clapston;Drama|6
Mark Gannicott;Drama|4
Brigit Loudiane;Comedy|3
Nicholas Duckfield;Drama|9
Val Beri;Drama|1
Daphne Hartell;Drama|2
Merle McBayne;Comedy|3
Ursola Kerr;Comedy|2
Gran Elkington;Drama|3
Quintus Markson;Drama|3
Merrie Joseph;Drama|5
Randi Crowdson;Drama|6
Joanna Skellern;Comedy|4
Lily Cattroll;Comedy|2
Aurelie Ankers;Drama|3
Rhoda Russan;Drama|3
Berry Matiewe;Comedy|3;Drama|2
Elladine Marley;Drama|2
Shaina Cicculini;Comedy|3;Drama|4
Clare Farthin;Drama|3
Levi Avrahamof;Drama|3
Shelby Arnaudin;Comedy|2
Dominique Nudd;Comedy|4
Sondra Roberts;Comedy|4
Sibyl Zelland;Drama|4
Matt Lonsbrough;Drama|2
Constantia Retallick;Comedy|4;Drama|6
Phillipe Augar;Comedy|2
Edie Larrett;Drama|3
Jenn Whatling;Comedy|1
Trula Wills;Comedy|4
Aretha Rapp;Drama|3
Alexis Ketteman;Comedy|1;Drama|1
Ladonna Slograve;Drama|4
Elmira Birkin;Comedy|3
Jerrie Scamerden;Drama|2
Marlie Pietzker;Drama|2
Dorolisa Spere;Drama|2
Lida Barthelme;Comedy|3
Randy Asch;Comedy|3
Gloriana Espadero;Comedy|3
Balduin Schmidt;Drama|1
Nate Pley;Comedy|1
Pauly Aizik;Comedy|7
Jerrylee Moncrieffe;Drama|1
Dorey Normanell;Comedy|2
Anya Leate;Comedy|1
Nikolos McPhail;Comedy|3
Flori Valentin;Drama|3
Catherine Josefsson;Drama|1
Palmer Grestie;Drama|5
Devina Challice;Drama|5
Nerte Elgy;Drama|4
Zacherie Lindro;Drama|4
Pavia Brasner;Comedy|2
Nalani Wyness;Comedy|1
Tabbie Handslip;Comedy|3
Cal Findlay;Drama|3
Dela Drysdell;Comedy|2
Dore Luckman;Comedy|2
Whittaker McEntee;Drama|5
Bette Sarson;Comedy|1
Hew Thon;Drama|3
Andie Snalum;Comedy|3;Drama|4
Selma Pelfer;Drama|4
Osborn Gauler;Comedy|2;Drama|1
Imogen Yu;Comedy|3
Magdalena Strotone;Drama|6
Benyamin Stallion;Comedy|2;Drama|4
Susie Oby;Comedy|1
Lucine Pargeter;Comedy|1
Emelda Frise;Drama|2
Wilma McCullen;Drama|3
Godart Linnitt;Comedy|2;Drama|3
Francisca Rowler;Drama|2
Andras Woolsey;Drama|3
Guthrie Troutbeck;Drama|2
Thurston Strank;Drama|2
Kayley Perot;Comedy|1
Earle Burgott;Comedy|3;Drama|6
Ivy Belison;Comedy|2
Izzy McPike;Drama|5
Ramsey Gummary;Comedy|3;Drama|2
Ara Arnke;Drama|5
Merv Guerner;Comedy|3
Cherilyn Iskowitz;Drama|3
Gino Wellard;Comedy|3
Nerty Andreassen;Drama|5
Whitney Adolfsen;Comedy|2
Sophronia Dunne;Comedy|1
Tymothy Hindsberg;Drama|4
Biddy Hanvey;Drama|4
Carly Lynd;Drama|1
Lurline Pottery;Drama|2
Preston Metts;Comedy|2;Drama|2
Addie Bees;Comedy|4
Rivkah D'Antonio;Comedy|1;Drama|1
Mable Lapides;Drama|1
Ree Girardet;Comedy|3
Jerry Ianno;Comedy|1
Director;Drama|1
Kalinda Bruinsma;Drama|1
Kristien Batrip;Comedy|1
Jeannette Gatlin;Drama|2
Celestine Simmill;Drama|2
Nelie Moreing;Comedy|1;Drama|1
Melvyn Manneville;Drama|3
Heinrick Guitt;Comedy|3
Ninnette Halsted;Drama|2
Germayne Cullingford;Drama|1
Donn Grayland;Comedy|2;Drama|1
Tessy Mulqueen;Comedy|2;Drama|1
Guinevere Orton;Drama|2
Cheryl Bouch;Drama|5
Silvano Michelin;Comedy|1
Maurita Ganny;Comedy|2
Aldwin Copelli;Comedy|1;Drama|2
Egan Aspel;Drama|1
Jere Hastelow;Drama|2
Christiano Ransom;Comedy|2
Sapphira Lambarth;Drama|1
Gustave Guice;Drama|1
Michel Ianitti;Drama|2
Yehudi Lippiello;Drama|3
Tamera Minguet;Comedy|3;Drama|3
Salomone Prime;Drama|1
Dana Bacher;Drama|1
Nert Fruchon;Comedy|1
Carmelia Chewter;Drama|3
Aggie Kennewell;Drama|2
Poul Yelland;Comedy|1;Drama|1
Celestyn Wooldridge;Comedy|1;Drama|1
Guido McWard;Comedy|1
Rem Jacquemy;Comedy|2
Ileane Madrell;Drama|1
Mendel Hawk;Drama|2
Florella Tomanek;Drama|2
Wendeline Shenton;Drama|2
Cleavland Vinker;Drama|1
Ardisj Rosenbarg;Drama|1
Rowan Delle;Drama|1
Pia Christoforou;Drama|1
Nonnah Inwood;Drama|1
Shaun Bahia;Comedy|1;Drama|1
Myra Dufaire;Comedy|1
Tabatha Broun;Comedy|1
Vance Bartkowiak;Comedy|2
Verine McParlin;Comedy|1
Aleda Slowgrave;Drama|1
Rebeka Zupo;Comedy|1
Aloysia Bowdery;Comedy|1
Willy Lemmanbie;Drama|1
Quinta Keepe;Drama|1
